### ISSUE TITLE
Slacktee posts to `slackbot` and not my actual user

### ISSUE THREAD

**Issue by hobakill** [course-hero/slacktee#29] opened 2016-07-21 21:53 UTC
So I've set up my  `.slacktee` file to post to me on slack: 

`username="@myusername"`

However, when I do the simple `ls` example, slacktee sends it to `slackbot` instead. What am I missing? 

![screen shot 2016-07-21 at 4 52 12 pm](https://cloud.githubusercontent.com/assets/4466324/17040119/9ea8ed1c-4f63-11e6-85a0-76327a356db4.png)

**Comment by Chikashi-Kato** [comment] 2016-07-24 07:56
Sorry for the late reply. I'm confirming the behavior and get back to you, but I think that is a correct behavior. Since the sender of the message is a bot, receiving the message from slackbot makes sense for me. 
What is your expected behavior?

**Comment by Chikashi-Kato** [comment] 2016-07-26 01:54
Hi hobakill, I checked Slack's api and confirmed that is the expected behavior.
Since slacktee uses `Incoming Webhooks`, slacktee's message is sent to you as a message of `slackbot`.

> Post to an IM channel
> Posting to an IM channel is a little more complex depending on the value of as_user.
>
> If as_user is false:
> Pass a username (@chris) as the value of channel to post to that user's @slackbot channel as the bot.

https://api.slack.com/incoming-webhooks

I will close this issue, but please feel free to post your thoughts here :)
Thank you for using slacktee!

**Closed by Chikashi-Kato** 2016-07-26 01:54 UTC
Labels: question
